services:
  ldap:
    image: osixia/openldap:1.4.0
    environment:
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_TLS=false
    ports:
      - 389
    volumes:
      - type: bind
        source: ./scaffolding/ldap
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom/
    healthcheck:
      test: /usr/bin/ldapsearch -x -h localhost -b dc=example,dc=org cn=test,ou=users,dc=example,dc=org
    command: --loglevel debug --copy-service

  opensearch:
    image: opensearchproject/opensearch:2.2.0
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200
      - 9600
    healthcheck:
      test: >-
        curl --fail "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=1s" || exit 1
      interval: 5s
      timeout: 3s
      start_period: 30s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    links:
      - opensearch

  postgres:
    image: aweber/imbi-postgres:0.22.7
    ports:
      - 5432
    volumes:
      - ./scaffolding/postgres/z01-data.sql:/docker-entrypoint-initdb.d/z01-data.sql
      - ./scaffolding/postgres/z02-imbi-db.sh:/docker-entrypoint-initdb.d/z02-imbi-db.sh

  redis:
    image: redis:7-alpine
    ports:
      - 6379
    healthcheck:
      test: echo "PING" | nc redis 6379 | grep -q "PONG"

  test-python3.9:
    image: python:3.9-alpine
    links:
      - ldap
      - postgres
      - redis
    volumes:
      - ./:/source:ro
      - ./ci/config.yaml:/tmp/test/build/test.yaml:ro
    command: /source/ci/test.sh

  imbi:
    image: aweber/imbi:latest
    links:
      - ldap
      - postgres
      - redis
    ports:
      - 8000
    volumes:
      - ./ci/config.yaml:/etc/imbi/imbi.yaml
