# Prebuilt configuration file for use INSIDE of the docker compose environment
automations:
  consul:
    environments:
      "Development":
        datacenter: "development"
        token: "00000000-0000-0000-0000-000000000000"
        url: "http://consul:8500"
    templates:
      key_value_path: "/{namespace.slug}/{project_type.slug}/{project.slug}"
      service_url: "http://{project.slug}.services.{environment.datacenter}.consul"
http:
  canonical_server_name: imbi
  cookie_secret: imbi
  processes: 2
  xheaders: true
ldap:
  enabled: true
  host: ldap
  port: 389
  ssl: false
  groups_dn: ou=groups,dc=example,dc=org
  users_dn: ou=users,dc=example,dc=org
  username: cn
opensearch:
  redis_url: redis://redis:6379/2
  connection:
    hosts:
      - host: opensearch
        port: 9200
    use_ssl: false
postgres:
  url: postgres://postgres@postgres:5432/postgres
session:
  redis_url: redis://redis:6379/0
stats:
  redis_url: redis://redis:6379/1
logging:
  version: 1
  formatters:
    verbose:
      format: "%(levelname) -10s %(asctime)s %(name) -15s %(funcName) -15s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: verbose
  loggers:
    imbi.ldap:
      level: WARNING
    imbi.session:
      level: WARNING
    imbi.user:
      level: WARNING
    sprockets_postgres:
      level: WARNING
      propagate: true
      handlers: [console]
  root:
    level: INFO
    handlers: [console]
  disable_existing_loggers: false
  incremental: false
